spring.application.name=hackmate

server.port=8081


spring.datasource.url=jdbc:mysql://mysql-be9614a-hackmate-kavya.d.aivencloud.com:19671/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true